# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ww',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nozap', models.IntegerField(blank=True, null=True)),
                ('poznw', models.CharField(blank=True, max_length=30, null=True)),
                ('kol', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True)),
                ('poznd', models.CharField(blank=True, max_length=30, null=True)),
                ('kornd', models.CharField(blank=True, max_length=10, null=True)),
                ('kodm', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True)),
                ('kodp', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True)),
                ('rozma', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True)),
                ('rozmb', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True)),
                ('kolz', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('mar', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True)),
                ('kttp', models.CharField(blank=True, max_length=20, null=True)),
                ('kodo', models.CharField(blank=True, max_length=12, null=True)),
                ('invn', models.CharField(blank=True, max_length=7, null=True)),
                ('kto', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('kzp', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('rr', models.IntegerField(blank=True, null=True)),
                ('normw', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('tpz', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('oper', models.CharField(blank=True, max_length=12, null=True)),
                ('kzop', models.IntegerField(blank=True, null=True)),
                ('kzonop', models.IntegerField(blank=True, null=True)),
                ('data_z', models.DateTimeField(blank=True, null=True)),
                ('shw', models.IntegerField(blank=True, null=True)),
                ('shwz', models.CharField(blank=True, max_length=20, null=True)),
                ('nrmd', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('mz', models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('setka', models.IntegerField(blank=True, null=True)),
                ('wn', models.IntegerField(blank=True, null=True)),
                ('shbr', models.IntegerField(blank=True, null=True)),
                ('wag', models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('krno', models.IntegerField(blank=True, null=True)),
                ('nto', models.IntegerField(blank=True, null=True)),
                ('pri', models.IntegerField(blank=True, null=True)),
                ('koli', models.IntegerField(blank=True, null=True)),
                ('vb', models.IntegerField(blank=True, null=True)),
                ('proc', models.IntegerField(blank=True, null=True)),
                ('data_nd', models.IntegerField(blank=True, null=True)),
                ('data_od', models.IntegerField(blank=True, null=True)),
                ('vnd', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('vod', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('d_u', models.IntegerField(blank=True, null=True)),
                ('vidrab', models.IntegerField(blank=True, null=True)),
                ('dop', models.IntegerField(blank=True, null=True)),
                ('zav', models.IntegerField(blank=True, null=True)),
                ('kolzag', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True)),
                ('primech', models.CharField(blank=True, max_length=80, null=True)),
                ('pokr', models.CharField(blank=True, max_length=12, null=True)),
                ('gpokr', models.CharField(blank=True, max_length=12, null=True)),
                ('kodzag', models.IntegerField(blank=True, null=True)),
                ('twer', models.CharField(blank=True, max_length=8, null=True)),
                ('tocha', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('tochb', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('naimd', models.CharField(blank=True, max_length=70, null=True)),
            ],
            options={
                'db_table': 'ww',
                'managed': False,
            },
        ),
    ]
