from django.db import models

class Ww(models.Model):
    nozap = models.IntegerField(blank=True, null=True)
    poznw = models.CharField(max_length=30, blank=True, null=True)
    kol = models.DecimalField(max_digits=4, decimal_places=0, blank=True, null=True)
    poznd = models.CharField(max_length=30, blank=True, null=True)
    kornd = models.CharField(max_length=10, blank=True, null=True)
    kodm = models.DecimalField(max_digits=4, decimal_places=0, blank=True, null=True)
    kodp = models.DecimalField(max_digits=4, decimal_places=0, blank=True, null=True)
    rozma = models.DecimalField(max_digits=8, decimal_places=1, blank=True, null=True)
    rozmb = models.DecimalField(max_digits=8, decimal_places=1, blank=True, null=True)
    kolz = models.DecimalField(max_digits=4, decimal_places=1, blank=True, null=True)
    mar = models.DecimalField(max_digits=4, decimal_places=0, blank=True, null=True)
    kttp = models.CharField(max_length=20, blank=True, null=True)
    kodo = models.CharField(max_length=12, blank=True, null=True)
    invn = models.CharField(max_length=7, blank=True, null=True)
    kto = models.DecimalField(max_digits=5, decimal_places=0, blank=True, null=True)
    kzp = models.DecimalField(max_digits=5, decimal_places=0, blank=True, null=True)
    rr = models.IntegerField(blank=True, null=True)
    normw = models.DecimalField(max_digits=8, decimal_places=3, blank=True, null=True)
    tpz = models.DecimalField(max_digits=8, decimal_places=3, blank=True, null=True)
    oper = models.CharField(max_length=12, blank=True, null=True)
    kzop = models.IntegerField(blank=True, null=True)
    kzonop = models.IntegerField(blank=True, null=True)
    data_z = models.DateTimeField(blank=True, null=True)
    shw = models.IntegerField(blank=True, null=True)
    shwz = models.CharField(max_length=20, blank=True, null=True)
    nrmd = models.DecimalField(max_digits=15, decimal_places=5, blank=True, null=True)
    mz = models.DecimalField(max_digits=9, decimal_places=5, blank=True, null=True)
    setka = models.IntegerField(blank=True, null=True)
    wn = models.IntegerField(blank=True, null=True)
    shbr = models.IntegerField(blank=True, null=True)
    wag = models.DecimalField(max_digits=9, decimal_places=5, blank=True, null=True)
    krno = models.IntegerField(blank=True, null=True)
    nto = models.IntegerField(blank=True, null=True)
    pri = models.IntegerField(blank=True, null=True)
    koli = models.IntegerField(blank=True, null=True)
    vb = models.IntegerField(blank=True, null=True)
    proc = models.IntegerField(blank=True, null=True)
    data_nd = models.IntegerField(blank=True, null=True)
    data_od = models.IntegerField(blank=True, null=True)
    vnd = models.DecimalField(max_digits=4, decimal_places=2, blank=True, null=True)
    vod = models.DecimalField(max_digits=4, decimal_places=2, blank=True, null=True)
    d_u = models.IntegerField(blank=True, null=True)
    vidrab = models.IntegerField(blank=True, null=True)
    dop = models.IntegerField(blank=True, null=True)
    zav = models.IntegerField(blank=True, null=True)
    kolzag = models.DecimalField(max_digits=4, decimal_places=0, blank=True, null=True)
    primech = models.CharField(max_length=80, blank=True, null=True)
    pokr = models.CharField(max_length=12, blank=True, null=True)
    gpokr = models.CharField(max_length=12, blank=True, null=True)
    kodzag = models.IntegerField(blank=True, null=True)
    twer = models.CharField(max_length=8, blank=True, null=True)
    tocha = models.DecimalField(max_digits=3, decimal_places=2, blank=True, null=True)
    tochb = models.DecimalField(max_digits=3, decimal_places=2, blank=True, null=True)
    naimd = models.CharField(max_length=70, blank=True, null=True)

    def __str__(self):
        return self.shwz + ' ' + self.kornd

    class Meta:
        managed = False
        db_table = 'ww'

